// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace TestingMvvmX.iOS
{
	public partial class AViewController : UIViewController
	{
		public AViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
